version: '2'
services:
  db:
    image: postgres:9.5
    environment:
      - POSTGRES_USER:admin
      - POSTGRES_PASSWORD:admin
      - POSTGRES_DB:posts
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data
