# Generated by Django 3.0.3 on 2020-05-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalaryCalcAPI', '0003_auto_20200512_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='fix_commission',
            field=models.BooleanField(default=True),
        ),
    ]
