# Generated by Django 3.0.3 on 2020-05-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalaryCalcAPI', '0004_auto_20200512_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='simple_view',
            field=models.BooleanField(auto_created=True, default=True),
        ),
    ]
